config/routes.rb
App::Application.routes.draw do
  root 'posts#index'

  get    "autologin/:id" => "users#autologin",  as: :autologin
  delete "logout" => "users#destroy", as: :logout

  resources :posts
  resources :users

  TheCommentsBase::Routes.mixin(self)
  TheCommentsManager::Routes.mixin(self)
  TheCommentsSubscriptions::Routes.mixin(self)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ::TheCommentsBase::Comment
  # ---------------------------------------------------
  # Define comment's avatar url
  # Usually we use Comment#user (owner of comment) to define avatar
  # @blog.comments.includes(:user) <= use includes(:user) to decrease queries count
  # comment#user.avatar_url
  # ---------------------------------------------------

  # ---------------------------------------------------
  # Simple way to define avatar url

  # def avatar_url
  #   hash = Digest::MD5.hexdigest self.id.to_s
  #   "http://www.gravatar.com/avatar/#{hash}?s=30&d=identicon"
  # end
  # ---------------------------------------------------

  # ---------------------------------------------------
  # Define your filters for content
  # Expample for: gem 'RedCloth', gem 'sanitize'
  # your personal SmilesProcessor

  # def prepare_content
  #   text = self.raw_content
  #   text = RedCloth.new(text).to_html
  #   text = SmilesProcessor.new(text)
  #   text = Sanitize.clean(text, Sanitize::Config::RELAXED)
  #   self.content = text
  # end
  # ---------------------------------------------------
end

app/models/comment_subscription.rb
class CommentSubscription < ActiveRecord::Base
  include ::TheCommentsSubscriptions::Relations
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ::TheCommentsBase::Commentable

  belongs_to :user

  def commentable_title
    title
  end

  def commentable_url
    ['', self.class.to_s.tableize, id].join('/')
  end

  def commentable_state
    :published.to_s
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheCommentsBase::User
  include TheCommentsBase::Commentable

  authenticates_with_sorcery!

  has_many :posts

  # can be replaced to TheCommentsUser as default
  def admin?
    self == User.first
  end

  def comments_admin?
    admin?
  end

  def comments_moderator? comment
    id == comment.holder_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ::TheCommentsBase::ViewToken

  def comments_cookies_token
    'DefineYourTheCommentsCookies'
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  private

  def set_locale
    locale = 'en'
    langs  = %w{ en ru }

    if params[:locale]
      lang   = params[:locale]
      locale = cookies[:locale] = lang if langs.include?(lang)
    else
      if cookies[:locale]
        lang = cookies[:locale]
        locale = lang if langs.include?(lang)
      end
    end

    I18n.locale = locale
  end
end

app/controllers/comment_subscriptions_controller.rb
class CommentSubscriptionsController < ApplicationController
  include ::TheCommentsSubscriptions::Controller
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # Define your restrict methods and use them like this:
  #
  # before_action :user_required,      except: [:index, :create]
  #
  # before_action :owner_required,     only: [:my, :incoming, :edit, :trash]
  # before_action :moderator_required, only: [:update, :to_published, :to_draft, :to_spam, :to_trash]

  layout 'admin'

  include ::TheCommentsBase::Controller

  # Public methods:
  #
  # [:index, :create]

  # Application side methods:
  # Overwrite following default methods if it's need
  # Following methods based on *current_user* helper method
  # Look here: https://github.com/the-teacher/the_comments/blob/master/app/controllers/concerns/the_comments_controller.rb#L62
  #
  # [:my, :incoming, :edit, :trash]

  # You must protect following methods
  # Only comments moderator (holder or admin) can invoke following actions
  #
  # [:update, :to_published, :to_draft, :to_spam, :to_trash]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @users = User.all

    @recent_comments = Comment.with_state(:published)
                       .includes(:commentable)
                       .recent.page(params[:page])
                       .where(commentable_state: [:published])
  end

  def show
    @post     = Post.find params[:id]
    @comments = @post.comments.with_state([:draft, :published]).nested_set
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def autologin
    user = User.find params[:id]
    auto_login user if user
    redirect_to request.referrer || root_path
  end

  def show
    @user = User.find params[:id]
    @comments = @user.comments.with_state([:draft, :published]).nested_set
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/admin.html.haml
!!! 5
%html(lang="ru")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Admin Panel"
    %link(href="favicon.ico" rel="shortcut icon")

    = stylesheet_link_tag    :admin_panel
    = javascript_include_tag :admin_panel
    = csrf_meta_tags

  %body
    .container
      .row
        .col-md-12
          %h3= content_for?(:title) ? yield(:title) : "Admin Panel"
      .row
        .col-md-3
          = yield :comments_sidebar
        .col-md-9
          = yield :comments_main

    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"

app/views/layouts/application.html.haml
!!!
%html{ data: { the_log: Rails.env.development? } }
%head
  %title TheComments Dummy App
  = stylesheet_link_tag    :application, media: :all
  = javascript_include_tag :application
  = csrf_meta_tags

%body
  .body
    = render partial: 'the_notification/flash', locals: { format: :json }

    %p
      = link_to 'Home', root_path
      \|
      - if current_user
        User: #{current_user.username}
        \|
        = link_to "Comments Manage (+#{current_user.draft_comcoms_count})", manage_comments_path
        \|
        = link_to 'Logout', logout_path, method: :delete
      - else
        Guest
    = yield

app/views/posts/index.html.haml
%h3 Posts:
%ul
  - @posts.each do |post|
    %li
      = link_to post_url(post) do
        = "#{post.title} (#{post.comments_sum})"

%h3 Users:
%ul
  - @users.each do |user|
    %li
      = link_to user_url(user) do
        = "#{user.username} (#{user.comments_sum})"

%h3 Autologin Users:
%ul
  - User.all.each do |user|
    %li
      = link_to autologin_url(user) do
        - admin = user.comments_admin? ? '[Admin]' : nil
        = "#{user.username} (#{user.draft_comcoms_count}) #{admin}"

%h3 Recent Comments:
%ul
  - @recent_comments.each do |comment|
    %p
      %i= comment.commentable.class
      %b= link_to comment.commentable_title, comment.commentable_url
      %br
      %i= comment.content

%hr
%h3 Unsubscribe links:

%hr
%p
  %b
    User.last / Comment.last
- if @last_comment = Comment.last
  %p= link_to "Unsub comment",     unsubscribe_comment_path(EncryptorHelper.crypt('user'), EncryptorHelper.crypt(@last_comment.id), EncryptorHelper.crypt(User.last.id))
  %p= link_to "Unsub commentable", unsubscribe_commentable_path(EncryptorHelper.crypt('user'), EncryptorHelper.crypt(@last_comment.id), EncryptorHelper.crypt(User.last.id))

%p= link_to "Unsub all",         unsubscribe_all_path(EncryptorHelper.crypt('user'), EncryptorHelper.crypt(User.first.id))

%hr
%p
  %b
    email test@test.com / Comment.last

- if @last_comment = Comment.last
  %p= link_to "Unsub comment",     unsubscribe_comment_path(EncryptorHelper.crypt('user'),  EncryptorHelper.crypt(@last_comment.id), EncryptorHelper.crypt(User.first.id))
  %p= link_to "Unsub commentable", unsubscribe_commentable_path(EncryptorHelper.crypt('email'), EncryptorHelper.crypt(@last_comment.id), EncryptorHelper.crypt("test@email.com"))
%p= link_to "Unsub all",         unsubscribe_all_path( EncryptorHelper.crypt('user'), EncryptorHelper.crypt(User.first.id))

app/views/posts/show.html.haml
%h3= @post.title
%p=  @post.content

%p
  Comments count:
  %span{ data: { role: :comments_sum } }= @post.comments_sum

= render partial: the_comments_template('tree'), locals: { commentable: @post, comments_tree: @comments }

app/views/users/show.html.haml
%h3= @user.username

%p Profile Info

%p
  Comments count:
  %span{ data: { role: :comments_sum } }= @user.comments_sum

= render partial: the_comments_template('tree'), locals: { commentable: @user, comments_tree: @comments }